#!/bin/bash
#PBS -l nodes=1:ppn=1,vmem=12gb,walltime=1:30:00
#PBS -N app-thalamic-segmentation

echo $FREESURFER_LICENSE > license.txt
time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/freesurfer:dev ./run.sh

