#!/bin/bash
#PBS -l nodes=1:ppn=8,vmem=14gb,walltime=2:00:00
#PBS -N app-thalamic-segmentation

echo $FREESURFER_LICENSE > license.txt
time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/freesurfer:dev ./run.sh

